version: "3.8"

services:
  nginx:
    build: "./nginx"
    container_name: "nginx_reverse_proxy"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/etc/nginx/certs/
    networks:
      - app
    links:
      - node1
  
  node1:
    build: "./node"
    container_name: node1
    ports:
      - 4000:4000
    networks:
      - database
      - app
    links:
      - mongodb
    depends_on:
      - mongodb
  
  node2:
      build: "./node"
      container_name: node2
      ports:
        - 4001:4000
      networks:
        - database
        - app
      links:
        - mongodb
      depends_on:
        - mongodb
  
  node3:
      build: "./node"
      container_name: node3
      ports:
        - 4002:4000
      networks:
        - database
        - app
      links:
        - mongodb
      depends_on:
        - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo/datamongo:/data/db
    networks:
      - database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nutriverse

  react1:
    build: "./nutriverse"
    container_name: "react1"
    ports:
      - 3000:3000
    networks:
      - app
    volumes:
      - ./nutriverse/src:/app/src

  react2:
    build: "./nutriverse"
    container_name: "react2"
    ports:
      - 3001:3000
    networks:
      - app
    volumes:
      - ./nutriverse/src:/app/src
   
networks:
  database:
  app:
