version: "3.8"

services:
  nginx:
    build: "./nginx"
    container_name: "nginx_reverse_proxy"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/etc/nginx/certs/
    networks:
      - app
    links:
      - node1

  node1:
    build: "./node"
    container_name: node1
    ports:
      - 4000:4000
    volumes:
      - ./node:/app
    networks:
      - database
      - app
    links:
      - mongodb
    depends_on:
      - mongodb

  react1:
    build: "./nutriverse"
    container_name: "react1"
    ports:
      - 5174:3000
    volumes:
      - ./nutriverse/src:/app/src
    networks:
      - app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo/datamongo:/data/db
    networks:
      - database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nutriverse
  
networks:
  database:
  app:
