version: "3.8"

services:
  node:
    build: "./node"
    container_name: node
    ports:
      - 4000:4000
    volumes:
      - ./node:/app
    networks:
      - database
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo/datamongo:/data/db
    networks:
      - database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nutriverse
  
networks:
  database:
